FROM node:20-alpine

ARG AUTH_MICROSOFT_ENTRA_ID_ID
ARG AUTH_MICROSOFT_ENTRA_ID_SECRET
ARG AUTH_MICROSOFT_ENTRA_ID_TENANT_ID
ARG AUTH_SECRET
ARG AUTH_TRUST_HOST
ARG AUTH_URL
ARG DATABASE_URL
ARG OPENAI_API_KEY
ARG PINECONE_API_KEY
ARG PINECONE_ENVIRONMENT
ARG PINECONE_INDEX_NAME
ARG INDEX_INIT_TIMEOUT
ARG ARCJET_KEY

ENV AUTH_MICROSOFT_ENTRA_ID_ID ${AUTH_MICROSOFT_ENTRA_ID_ID}
ENV AUTH_MICROSOFT_ENTRA_ID_SECRET ${AUTH_MICROSOFT_ENTRA_ID_SECRET}
ENV AUTH_MICROSOFT_ENTRA_ID_TENANT_ID ${AUTH_MICROSOFT_ENTRA_ID_TENANT_ID}
ENV AUTH_SECRET ${AUTH_SECRET}
ENV AUTH_TRUST_HOST ${AUTH_TRUST_HOST}
ENV AUTH_URL ${AUTH_URL}
ENV DATABASE_URL ${DATABASE_URL}
ENV OPENAI_API_KEY ${OPENAI_API_KEY}
ENV PINECONE_API_KEY ${PINECONE_API_KEY}
ENV PINECONE_ENVIRONMENT ${PINECONE_ENVIRONMENT}
ENV PINECONE_INDEX_NAME ${PINECONE_INDEX_NAME}
ENV INDEX_INIT_TIMEOUT ${INDEX_INIT_TIMEOUT}
ENV ARCJET_KEY ${ARCJET_KEY}

WORKDIR /usr/app

COPY . .

RUN npm ci

RUN npm run build

CMD [ "npm", "start" ]
