FROM node:20-alpine

ARG AUTH_MICROSOFT_ENTRA_ID_ID
ARG AUTH_MICROSOFT_ENTRA_ID_SECRET
ARG AUTH_MICROSOFT_ENTRA_ID_TENANT_ID
ARG AUTH_SECRET

ENV AUTH_MICROSOFT_ENTRA_ID_ID ${AUTH_MICROSOFT_ENTRA_ID_ID}
ENV AUTH_MICROSOFT_ENTRA_ID_SECRET ${AUTH_MICROSOFT_ENTRA_ID_SECRET}
ENV AUTH_MICROSOFT_ENTRA_ID_TENANT_ID ${AUTH_MICROSOFT_ENTRA_ID_TENANT_ID}
ENV AUTH_SECRET ${AUTH_SECRET}

WORKDIR /usr/app

COPY . .

RUN npm ci

RUN npm run build

CMD [ "npm", "start" ]
