import { Document } from "./document.type";

export const data: Document[] = [
  {
    id: 1,
    name: "2022-1 DIRECTIVA CURSOS PROYECTO I y II JULIO2022",
    size: 3.16,
    type: "Directiva",
    uploadDate: "22 de julio de 2024",
    isGlobal: false,
    students: [],
    groupName: "G1",
    subjectName: "Trabajo de investigación I",
    semesterName: "2024-II",
  },
  {
    id: 1,
    name: "BITACORA_Ucharima_Valer_242_P2_S01aS02",
    size: 2.42,
    type: "Bitacora",
    uploadDate: "22 de julio de 2024",
    isGlobal: false,
    students: [],
    groupName: "G1",
    subjectName: "Trabajo de investigación I",
    semesterName: "2024-II",
  },
  {
    id: 1,
    name: "BITACORA_Ucharima_Valer_242_P2_S03",
    size: 8.37,
    type: "Bitacora",
    uploadDate: "21 de julio de 2024",
    isGlobal: false,
    students: [],
    groupName: "G1",
    subjectName: "Trabajo de investigación I",
    semesterName: "2024-II",
  },
  {
    id: 1,
    name: "Cronograma_EF_Proyecto_I",
    size: 8.74,
    type: "Cronograma",
    uploadDate: "20 de julio de 2024",
    isGlobal: false,
    students: [],
    groupName: "G1",
    subjectName: "Trabajo de investigación I",
    semesterName: "2024-II",
  },
  {
    id: 1,
    name: "Cronograma_EF_Proyecto_II",
    size: 7.21,
    type: "Cronograma",
    uploadDate: "20 de julio de 2024",
    isGlobal: false,
    students: [],
    groupName: "G1",
    subjectName: "Trabajo de investigación I",
    semesterName: "2024-II",
  },
];