import { Student } from "./student.type";

export const users: Student[] = [
  {
    id: "1",
    name: "Julio Ucharima",
    status: "Activo",
    phone: "+51 940048445",
    registrationNumber: "",
    email: "julio_ucharima@usmp.pe",
    group: "G23",
    mentor: "Jose Antonio Wu",
    semester: "string",
    subject: "string",
  },
  {
    id: "2",
    name: "Sandro Baldera",
    status: "Activo",
    phone: "+51 940048446",
    registrationNumber: "",
    email: "sandro_baldera@usmp.pe",
    group: "G09",
    mentor: "Jose Antonio Wu",
    semester: "string",
    subject: "string",
  },
  {
    id: "3",
    name: "Renato Valer",
    status: "Activo",
    phone: "+51 940048444",
    registrationNumber: "",
    email: "renato_valer@usmp.pe",
    group: "G23",
    mentor: "Jose Antonio Wu",
    semester: "string",
    subject: "string",
  },
];
