name: Build & Push to Azure Container Registry

on:
  push:
    branches: production
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@main

      # 2. Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build and push Docker image to ACR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            AUTH_MICROSOFT_ENTRA_ID_ID=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_ID }}
            AUTH_MICROSOFT_ENTRA_ID_SECRET=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_SECRET }}
            AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID }}
            AUTH_SECRET="${{ secrets.AUTH_SECRET }}"
            AUTH_TRUST_HOST=${{secrets.AUTH_TRUST_HOST}}
            AUTH_URL=${{secrets.AUTH_URL}}
          tags: ${{ secrets.ACR_ENDPOINT }}/proyecto2-frontend:latest
          file: ./Dockerfile
